2>build_SPIRV_errors.log cls 
mkdir asEngine_Shaders\shaderCSO 
cd asEngine_Shaders\shaderCSO 
mkdir spirv
cd .. 
cd .. 
cd 3rdPart 
cd shadercompilers 
dxc  ../../asEngine_Shaders/shaders\CS\bloomcombineCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/bloomcombineCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\bloomseparateCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/bloomseparateCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\blur_bilateral_float1CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/blur_bilateral_float1CS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\blur_bilateral_float4CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/blur_bilateral_float4CS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\blur_bilateral_unorm1CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/blur_bilateral_unorm1CS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\blur_bilateral_unorm4CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/blur_bilateral_unorm4CS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\blur_gaussian_float1CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/blur_gaussian_float1CS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\blur_gaussian_float4CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/blur_gaussian_float4CS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\blur_gaussian_unorm1CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/blur_gaussian_unorm1CS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\blur_gaussian_unorm4CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/blur_gaussian_unorm4CS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\bvh_hierarchyCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/bvh_hierarchyCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\bvh_primitivesCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/bvh_primitivesCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\bvh_propagateaabbCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/bvh_propagateaabbCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\chromatic_aberrationCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/chromatic_aberrationCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\colorgradeCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/colorgradeCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\copytexture2D_float4CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/copytexture2D_float4CS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\copytexture2D_float4_borderexpandCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/copytexture2D_float4_borderexpandCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\copytexture2D_unorm4CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/copytexture2D_unorm4CS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\copytexture2D_unorm4_borderexpandCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/copytexture2D_unorm4_borderexpandCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\depthoffield_kickjobsCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/depthoffield_kickjobsCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\depthoffield_mainCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/depthoffield_mainCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\depthoffield_main_cheap_CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/depthoffield_main_cheap_CS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\depthoffield_main_earlyexit_CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/depthoffield_main_earlyexit_CS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\depthoffield_neighborhoodMaxCOCCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/depthoffield_neighborhoodMaxCOCCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\depthoffield_postfilterCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/depthoffield_postfilterCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\depthoffield_prepassCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/depthoffield_prepassCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\depthoffield_prepass_earlyexit_CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/depthoffield_prepass_earlyexit_CS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\depthoffield_tileMaxCOC_horizontalCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/depthoffield_tileMaxCOC_horizontalCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\depthoffield_tileMaxCOC_verticalCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/depthoffield_tileMaxCOC_verticalCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\depthoffield_upsampleCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/depthoffield_upsampleCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\emittedparticle_emitCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/emittedparticle_emitCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\emittedparticle_emit_FROMMESH_CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/emittedparticle_emit_FROMMESH_CS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\emittedparticle_finishUpdateCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/emittedparticle_finishUpdateCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\emittedparticle_kickoffUpdateCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/emittedparticle_kickoffUpdateCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\emittedparticle_simulateCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/emittedparticle_simulateCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\emittedparticle_simulate_DEPTHCOLLISIONS_CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/emittedparticle_simulate_DEPTHCOLLISIONS_CS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\emittedparticle_simulate_SORTING_CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/emittedparticle_simulate_SORTING_CS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\emittedparticle_simulate_SORTING_DEPTHCOLLISIONS_CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/emittedparticle_simulate_SORTING_DEPTHCOLLISIONS_CS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\emittedparticle_sphdensityCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/emittedparticle_sphdensityCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\emittedparticle_sphforceCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/emittedparticle_sphforceCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\emittedparticle_sphpartitionCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/emittedparticle_sphpartitionCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\emittedparticle_sphpartitionoffsetsCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/emittedparticle_sphpartitionoffsetsCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\emittedparticle_sphpartitionoffsetsresetCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/emittedparticle_sphpartitionoffsetsresetCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\fft_512x512_c2c_CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/fft_512x512_c2c_CS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\fft_512x512_c2c_v2_CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/fft_512x512_c2c_v2_CS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\filterEnvMapCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/filterEnvMapCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\fxaaCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/fxaaCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\generateMIPChain2D_float4_BicubicCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/generateMIPChain2D_float4_BicubicCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\generateMIPChain2D_float4_GaussianCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/generateMIPChain2D_float4_GaussianCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\generateMIPChain2D_float4_SimpleFilterCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/generateMIPChain2D_float4_SimpleFilterCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\generateMIPChain2D_unorm4_BicubicCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/generateMIPChain2D_unorm4_BicubicCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\generateMIPChain2D_unorm4_GaussianCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/generateMIPChain2D_unorm4_GaussianCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\generateMIPChain2D_unorm4_SimpleFilterCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/generateMIPChain2D_unorm4_SimpleFilterCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\generateMIPChain3D_float4_SimpleFilterCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/generateMIPChain3D_float4_SimpleFilterCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\generateMIPChain3D_unorm4_SimpleFilterCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/generateMIPChain3D_unorm4_SimpleFilterCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\generateMIPChainCubeArray_float4_SimpleFilterCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/generateMIPChainCubeArray_float4_SimpleFilterCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\generateMIPChainCubeArray_unorm4_SimpleFilterCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/generateMIPChainCubeArray_unorm4_SimpleFilterCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\generateMIPChainCube_float4_SimpleFilterCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/generateMIPChainCube_float4_SimpleFilterCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\generateMIPChainCube_unorm4_SimpleFilterCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/generateMIPChainCube_unorm4_SimpleFilterCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\gpusortlib_kickoffSortCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/gpusortlib_kickoffSortCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\gpusortlib_sortCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/gpusortlib_sortCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\gpusortlib_sortInnerCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/gpusortlib_sortInnerCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\gpusortlib_sortStepCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/gpusortlib_sortStepCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\hairparticle_simulateCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/hairparticle_simulateCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\lightCulling_ADVANCED_CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/lightCulling_ADVANCED_CS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\lightCulling_ADVANCED_DEBUG_CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/lightCulling_ADVANCED_DEBUG_CS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\lightCulling_CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/lightCulling_CS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\lightCulling_DEBUG_CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/lightCulling_DEBUG_CS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\lightCulling_DEFERRED_ADVANCED_CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/lightCulling_DEFERRED_ADVANCED_CS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\lightCulling_DEFERRED_ADVANCED_DEBUG_CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/lightCulling_DEFERRED_ADVANCED_DEBUG_CS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\lightCulling_DEFERRED_CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/lightCulling_DEFERRED_CS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\lightCulling_DEFERRED_DEBUG_CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/lightCulling_DEFERRED_DEBUG_CS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\lightShaftsCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/lightShaftsCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\lineardepthCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/lineardepthCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\luminancePass1CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/luminancePass1CS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\luminancePass2CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/luminancePass2CS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\motionblurCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/motionblurCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\motionblur_cheap_CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/motionblur_cheap_CS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\motionblur_earlyexit_CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/motionblur_earlyexit_CS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\motionblur_kickjobsCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/motionblur_kickjobsCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\motionblur_neighborhoodMaxVelocityCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/motionblur_neighborhoodMaxVelocityCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\motionblur_tileMaxVelocity_horizontalCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/motionblur_tileMaxVelocity_horizontalCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\motionblur_tileMaxVelocity_verticalCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/motionblur_tileMaxVelocity_verticalCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\oceanSimulatorCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/oceanSimulatorCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\oceanUpdateDisplacementMapCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/oceanUpdateDisplacementMapCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\oceanUpdateGradientFoldingCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/oceanUpdateGradientFoldingCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\outline_float4_CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/outline_float4_CS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\outline_unorm4_CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/outline_unorm4_CS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\raytrace_closesthitCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/raytrace_closesthitCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\raytrace_kickjobsCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/raytrace_kickjobsCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\raytrace_launchCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/raytrace_launchCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\raytrace_shadeCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/raytrace_shadeCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\raytrace_tilesortCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/raytrace_tilesortCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\resolveMSAADepthStencilCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/resolveMSAADepthStencilCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\sharpenCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/sharpenCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\skinningCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/skinningCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\skinning_LDS_CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/skinning_LDS_CS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\ssaoCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/ssaoCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\ssrCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/ssrCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\temporalaaCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/temporalaaCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\tileFrustumsCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/tileFrustumsCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\tonemapCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/tonemapCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\voxelClearOnlyNormalCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/voxelClearOnlyNormalCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\voxelRadianceSecondaryBounceCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/voxelRadianceSecondaryBounceCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\voxelSceneCopyClearCS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/voxelSceneCopyClearCS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\CS\voxelSceneCopyClear_TemporalSmoothing_CS.hlsl -T cs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_CS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/voxelSceneCopyClear_TemporalSmoothing_CS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\DS\objectDS.hlsl -T ds_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_DS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/objectDS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\GS\lensFlareGS.hlsl -T gs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_GS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/lensFlareGS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\GS\object_voxelizer_GS.hlsl -T gs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_GS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_voxelizer_GS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\GS\voxelGS.hlsl -T gs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_GS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/voxelGS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\HS\objectHS.hlsl -T hs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_HS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/objectHS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\captureImpostor_albedo_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/captureImpostor_albedo_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\captureImpostor_normal_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/captureImpostor_normal_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\captureImpostor_surface_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/captureImpostor_surface_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\circlePS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/circlePS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\cubeMapPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/cubeMapPS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\decalPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/decalPS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\deferredPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/deferredPS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\dirLightPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/dirLightPS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\discLightPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/discLightPS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\downsampleDepthBuffer4xPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/downsampleDepthBuffer4xPS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\emittedparticle_simplest_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/emittedparticle_simplest_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\emittedparticle_soft_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/emittedparticle_soft_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\emittedparticle_soft_distortion_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/emittedparticle_soft_distortion_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\envMapPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/envMapPS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\envMap_sky_dynamic_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/envMap_sky_dynamic_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\envMap_sky_static_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/envMap_sky_static_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\environmentalLightPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/environmentalLightPS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\fontPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/fontPS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\forceFieldVisualizerPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/forceFieldVisualizerPS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\hairparticle_alphatestonly_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/hairparticle_alphatestonly_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\hairparticle_deferred_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/hairparticle_deferred_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\hairparticle_forward_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/hairparticle_forward_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\hairparticle_forward_transparent_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/hairparticle_forward_transparent_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\hairparticle_simplest_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/hairparticle_simplest_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\hairparticle_tiledforward_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/hairparticle_tiledforward_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\hairparticle_tiledforward_transparent_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/hairparticle_tiledforward_transparent_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\imagePS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/imagePS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\image_bicubic_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/image_bicubic_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\image_masked_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/image_masked_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\image_masked_bicubic_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/image_masked_bicubic_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\image_separatenormalmap_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/image_separatenormalmap_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\image_separatenormalmap_bicubic_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/image_separatenormalmap_bicubic_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\impostor_alphatestonly_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/impostor_alphatestonly_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\impostor_deferred_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/impostor_deferred_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\impostor_forward_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/impostor_forward_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\impostor_simple_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/impostor_simple_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\impostor_tiledforward_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/impostor_tiledforward_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\impostor_wire_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/impostor_wire_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\lensFlarePS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/lensFlarePS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\lightVisualizerPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/lightVisualizerPS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\linesPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/linesPS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_alphatestonly_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_alphatestonly_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_blackout_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_blackout_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_debug_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_debug_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_deferred_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_deferred_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_deferred_normalmap_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_deferred_normalmap_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_deferred_normalmap_planarreflection_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_deferred_normalmap_planarreflection_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_deferred_normalmap_pom_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_deferred_normalmap_pom_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_deferred_planarreflection_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_deferred_planarreflection_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_deferred_pom_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_deferred_pom_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_forward_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_forward_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_forward_normalmap_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_forward_normalmap_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_forward_normalmap_planarreflection_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_forward_normalmap_planarreflection_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_forward_normalmap_pom_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_forward_normalmap_pom_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_forward_planarreflection_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_forward_planarreflection_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_forward_pom_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_forward_pom_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_forward_transparent_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_forward_transparent_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_forward_transparent_normalmap_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_forward_transparent_normalmap_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_forward_transparent_normalmap_planarreflection_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_forward_transparent_normalmap_planarreflection_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_forward_transparent_normalmap_pom_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_forward_transparent_normalmap_pom_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_forward_transparent_planarreflection_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_forward_transparent_planarreflection_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_forward_transparent_pom_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_forward_transparent_pom_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_forward_water_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_forward_water_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_hologram_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_hologram_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_simplest_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_simplest_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_textureonly_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_textureonly_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_tiledforward_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_tiledforward_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_tiledforward_normalmap_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_tiledforward_normalmap_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_tiledforward_normalmap_planarreflection_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_tiledforward_normalmap_planarreflection_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_tiledforward_normalmap_pom_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_tiledforward_normalmap_pom_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_tiledforward_planarreflection_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_tiledforward_planarreflection_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_tiledforward_pom_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_tiledforward_pom_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_tiledforward_transparent_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_tiledforward_transparent_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_tiledforward_transparent_normalmap_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_tiledforward_transparent_normalmap_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_tiledforward_transparent_normalmap_planarreflection_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_tiledforward_transparent_normalmap_planarreflection_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_tiledforward_transparent_normalmap_pom_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_tiledforward_transparent_normalmap_pom_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_tiledforward_transparent_planarreflection_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_tiledforward_transparent_planarreflection_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_tiledforward_transparent_pom_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_tiledforward_transparent_pom_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_tiledforward_water_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_tiledforward_water_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\object_voxelizer_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_voxelizer_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\oceanSurfacePS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/oceanSurfacePS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\oceanSurfaceSimplePS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/oceanSurfaceSimplePS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\pointLightPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/pointLightPS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\raytrace_debugbvhPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/raytrace_debugbvhPS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\rectangleLightPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/rectangleLightPS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\renderlightmapPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/renderlightmapPS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\screenPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/screenPS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\screen_bicubic_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/screen_bicubic_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\shadow_alphatest_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/shadow_alphatest_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\shadow_transparent_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/shadow_transparent_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\shadow_water_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/shadow_water_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\sky_dynamic_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/sky_dynamic_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\sky_static_PS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/sky_static_PS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\sphereLightPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/sphereLightPS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\spotLightPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/spotLightPS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\sssPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/sssPS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\sunPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/sunPS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\trailPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/trailPS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\tubeLightPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/tubeLightPS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\volumetricLight_DirectionalPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/volumetricLight_DirectionalPS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\volumetricLight_PointPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/volumetricLight_PointPS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\volumetricLight_SpotPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/volumetricLight_SpotPS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\PS\voxelPS.hlsl -T ps_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_PS -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/voxelPS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\cubeShadowVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/cubeShadowVS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\cubeShadow_alphatest_VS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/cubeShadow_alphatest_VS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\cubeVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/cubeVS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\decalVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/decalVS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\dirLightVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/dirLightVS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\emittedparticleVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/emittedparticleVS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\envMapVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/envMapVS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\envMap_skyVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/envMap_skyVS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\fontVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/fontVS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\forceFieldPlaneVisualizerVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/forceFieldPlaneVisualizerVS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\forceFieldPointVisualizerVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/forceFieldPointVisualizerVS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\hairparticleVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/hairparticleVS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\imageVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/imageVS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\impostorVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/impostorVS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\lensFlareVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/lensFlareVS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\linesVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/linesVS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\object_common_VS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_common_VS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\object_common_tessellation_VS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_common_tessellation_VS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\object_debug_VS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_debug_VS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\object_positionstream_VS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_positionstream_VS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\object_simple_VS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_simple_VS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\object_simple_tessellation_VS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_simple_tessellation_VS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\object_voxelizer_VS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/object_voxelizer_VS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\oceanSurfaceVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/oceanSurfaceVS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\pointLightVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/pointLightVS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\raytrace_screenVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/raytrace_screenVS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\renderlightmapVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/renderlightmapVS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\screenVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/screenVS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\shadowVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/shadowVS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\shadow_alphatest_VS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/shadow_alphatest_VS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\shadow_transparent_VS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/shadow_transparent_VS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\skyVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/skyVS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\sphereVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/sphereVS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\spotLightVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/spotLightVS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\trailVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/trailVS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\vDiscLightVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/vDiscLightVS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\vPointLightVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/vPointLightVS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\vRectangleLightVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/vRectangleLightVS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\vSphereLightVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/vSphereLightVS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\vSpotLightVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/vSpotLightVS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\vTubeLightVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/vTubeLightVS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\voxelVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/voxelVS.cso  2>>../../build_SPIRV_errors.log 
dxc  ../../asEngine_Shaders/shaders\VS\waterVS.hlsl -T vs_6_0 -D SHADERCOMPILER_SPIRV -D SPIRV_SHADERTYPE_VS -fvk-invert-y -spirv -fvk-use-dx-layout -flegacy-macro-expansion -Fo ../../asEngine_Shaders/shaderCSO/spirv/waterVS.cso  2>>../../build_SPIRV_errors.log 
cd .. 
